--remove table if it exists
drop table if exists bookmarks;

--create a new table
create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title text not null,
    url text not null,
    description text not null,
    rating INTEGER
);

--insert test data
insert into bookmarks (title, url, description, rating)
values
    ('Youtube', 'www.Youtube.com', 'Many Many videos', '5'),
    ('Facebook', 'www.Facebook.com', 'Connect with Family', '3'),
    ('Google', 'www.google.com', 'All the answers', '5'), 
    ('Reddit', 'www.reddit.com', 'Memes', '5'),
    ('Gmail', 'www.gmail.com', 'Emails!', '4'),
    ('Amazon', 'www.amazon.com', 'All our shopping needs', '5')